name: Check Azure ML Version

on:
  workflow_dispatch:
jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Check Azure ML version
        run: az extension show -n ml
