name: BDL Code checks

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - "main"

jobs:
  job1:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        run: |
          echo "Code checks will be implemented later"
